import "TreeItemViewModel.idl";

namespace TreeViewExample
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        TreeItemViewModel RootTreeItem{ get; };
    }
}
